# Generated by Django 3.2.24 on 2024-02-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240228_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_flower_count',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
