# Generated by Django 3.2.24 on 2024-02-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_flowercount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowercount',
            name='name',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
